


GET http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

### Users 
POST http://localhost:3000/users
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "hashedpassword123"
}

POST http://localhost:3000/users/login
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "hashedpassword13"
}


### Add a New Task
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "workspaceId": 1,
    "title": "Water Title",
    "description": "This is a new task description.",
    "startDate": "2024-11-13",
    "dueDate": "2024-11-15",
    "assignedTo": "Mdu"
}

### Update an Existing Task
PUT http://localhost:3000/tasks/1
Content-Type: application/json

{
    "title": "Updated Task Title",
    "status": "Completed"
}

### Delete a Task
DELETE http://localhost:3000/tasks/6

### Get All Tasks
GET http://localhost:3000/tasks/6

### Create
POST http://localhost:3000/workspaces
Content-Type: application/json

{
    "workspaceName": "New Workspace",
    "description": "This is a new workspace."
}

### Select
GET http://localhost:3000/workspaces
